### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by tud** [Juanmcuello/jqgrid_for_rails#1]
solved sorry

**Comment by Juanmcuello** [comment]
I was taking a look at it and it seems the gem [rails3-jquery-autocomplete](https://github.com/crowdint/rails3-jquery-autocomplete) uses the gem [yajl-ruby](https://github.com/brianmario/yajl-ruby) . This last gem changes the way JSON is generated and breaks [jqgrid_for_rails](https://github.com/Juanmcuello/jqgrid_for_rails) gem. 

I think I'll report it as a bug because _yajl-ruby_ should behave exactly the same when compatibility is enabled, and _rails3-jquery-autocomplete_ enables it.

Just to know, how did you solve the problem?

**Comment by tud** [comment]
I used javascript :)
$('#drawings_list').setGridParam({
    onSelectRow: function() {
.....
}
